# .github/workflows/daily-notification.yml
name: Daily Calendar Notification

on:
  schedule:
    # 毎日21時（日本時間）= UTC 12時に実行
    - cron: '0 12 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Debug secrets
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        NOTIFY_CHANNEL_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "DISCORD_TOKEN exists: ${{ secrets.DISCORD_TOKEN != '' }}"
        echo "NOTIFY_CHANNEL_ID exists: ${{ secrets.NOTIFY_CHANNEL_ID != '' }}"
        echo "GOOGLE_SERVICE_ACCOUNT_KEY exists: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY != '' }}"
        if [ ! -z "$GOOGLE_SERVICE_ACCOUNT_KEY" ]; then
          echo "GOOGLE_SERVICE_ACCOUNT_KEY length: ${#GOOGLE_SERVICE_ACCOUNT_KEY}"
        fi
    
    - name: Run notification script
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        NOTIFY_CHANNEL_ID: ${{ secrets.NOTIFY_CHANNEL_ID }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      run: |
        python notification_script.py
