# .github/workflows/refresh-token.yml
name: Refresh Google Token

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-api-python-client
    
    - name: Create credentials.json
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Create current token.json
      run: |
        echo '${{ secrets.GOOGLE_TOKEN }}' > token.json
    
    - name: Refresh Google Token
      run: |
        python token_refresh.py